### ISSUE TITLE
Cannot find org.neo.smartcontract.framework:neo-devpack-java:jar:2.3.0 in central Maven repository

### ISSUE THREAD

**Issue by EgorKuts** [neo-project/examples-java#7]
When i'm trying to build project, i'm getting this message:  Failed to execute goal on project ico-template: Could not resolve dependencies for project org.neo.ico:ico-template:jar:1.0.0: Could not find artifact org.neo.smartcontract.framework:neo-devpack-java:jar:2.3.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]  . How to solve this issue? Thank you for advance

**Comment by peterszatmary** [comment]
Since yesterday the first neo artifact was sucessfuly uploaded to maven repository. 

It is working as org.neo:neo-devpack-java:jar:2.3.0

See please [neo-devpack-java info](https://search.maven.org/artifact/org.neo/neo-devpack-java/2.3.0/jar)

Please try it and if it is working for you, we can close this issue.
